version: '3'

services:
  db:
    image: postgres:11-alpine
    volumes:
    - postgres-volume:/var/lib/postgresql/data

  quiz-dev:
    build:
      context: ./app
      dockerfile: ./dockerfile/Dockerfile.dev
    image: quiz:dev
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
    - quiz-volume-sync:/app:nocopy
    ports:
    - '3000:3000'
    depends_on:
    - db

volumes:
  postgres-volume: {}
  quiz-volume-sync:
    external: true
